name: AG  Release Cloud

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for manual release'
        required: false
        default: 'latest'

env:
  # Common versions
  GO_VERSION: "1.20"
  DEFAULT_OWNER: "labring"

jobs:
  release-service:
    uses: ./.github/workflows/services.yml
    with:
      push_image: true
      push_image_tag: ${{ github.event.inputs.tag || github.event.release.tag_name }}
    secrets: inherit
    
  release-controllers:
    uses: ./.github/workflows/controllers.yml
    with:
      push_image: true
      push_image_tag: ${{ github.event.inputs.tag || github.event.release.tag_name }}
    secrets: inherit

  release-frontends:
    uses: ./.github/workflows/frontends.yml
    with:
      push_image: true
      push_image_tag: ${{ github.event.inputs.tag || github.event.release.tag_name }}
    secrets: inherit

  save-sealos:
    uses: ./.github/workflows/import-save-sealos.yml

  release-cloud:
    needs:
      - save-sealos
      - release-controllers
      - release-frontends
      - release-service
    uses: ./.github/workflows/cloud.yml
    with:
      push_image: true
      push_image_tag: ${{ github.event.inputs.tag || github.event.release.tag_name }}
      build_from: ${{ github.event.inputs.tag || github.event.release.tag_name }}
    secrets: inherit

  release-objectstorage:
    needs:
      - save-sealos
      - release-controllers
      - release-frontends
      - release-service
    uses: ./.github/workflows/objectstorage.yaml
    with:
      push_image: true
      push_image_tag: ${{ github.event.inputs.tag || github.event.release.tag_name }}
      build_from: ${{ github.event.inputs.tag || github.event.release.tag_name }}
    secrets: inherit
