name: AG  Release Cloud

on:
  workflow_call:
    inputs:
      push_image:
        description: "Push image"
        required: false
        type: boolean
        default: false
      push_image_tag:
        description: "Push image tag"
        default: "latest"
        required: false
        type: string
  workflow_dispatch:
    inputs:
      push_image:
        description: "Push image"
        required: false
        type: boolean
        default: false
      push_image_tag:
        description: "Push image tag"
        default: "latest"
        required: false
        type: string

env:
  # Common versions
  GO_VERSION: "1.20"
  DEFAULT_OWNER: "labring"

jobs:
  save-sealos:
    uses: ./.github/workflows/import-save-sealos.yml

  release-controllers:
    uses: ./.github/workflows/controllers.yml
    with:
      push_image: true
      push_image_tag: ${{ inputs.push_image_tag }}
    secrets: inherit

  release-frontends:
    uses: ./.github/workflows/frontend.yml
    with:
      push_image: true
      push_image_tag: ${{ inputs.push_image_tag }}
    secrets: inherit

  release-service:
    needs:
      - save-sealos
    uses: ./.github/workflows/services.yml
    with:
      push_image: true
      push_image_tag: ${{ inputs.push_image_tag }}
    secrets: inherit

  release-cloud:
    needs:
      - save-sealos
      - release-controllers
      - release-frontends
      - release-service
    uses: ./.github/workflows/cloud.yml
    with:
      push_image: true
      push_image_tag: ${{ inputs.push_image_tag }}
      build_from: ${{ inputs.push_image_tag }}
    secrets: inherit

  release-objectstorage:
    needs:
      - save-sealos
    uses: ./.github/workflows/objectstorage.yaml
    with:
      push_image: true
      push_image_tag: ${{ inputs.push_image_tag }}
      build_from: ${{ inputs.push_image_tag }}
    secrets: inherit
